# CMake generated Testfile for 
# Source directory: /home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore
# Build directory: /home/lukkyguy/code/NestBenchmark/nest-build/testsuite/regressiontests/sli2py_ignore
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regressiontests/sli2py_ignore/issue-2052.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/issue-2052.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/issue-2052.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-235.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-235.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-235.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-475.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-475.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-475.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-537.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-537.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-537.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-580.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-580.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-580.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-733.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-733.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-733.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-777.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-777.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-777.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-784.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-784.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-784.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-785.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-785.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-785.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[regressiontests/sli2py_ignore/ticket-787.sli]=] "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/bin/nest" "/home/lukkyguy/code/NestBenchmark/nest-simulator-install/share/doc/nest/regressiontests/sli2py_ignore/ticket-787.sli")
set_tests_properties([=[regressiontests/sli2py_ignore/ticket-787.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;24;add_test;/home/lukkyguy/code/NestBenchmark/nest-simulator/testsuite/regressiontests/sli2py_ignore/CMakeLists.txt;0;")
