# CMake generated Testfile for 
# Source directory: /p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore
# Build directory: /p/home/jusers/linssen1/jusuf/NestBenchmark/nest-build/testsuite/unittests/sli2py_ignore
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[unittests/sli2py_ignore/test_DoubleVector_IntVector.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_DoubleVector_IntVector.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_DoubleVector_IntVector.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_Map.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_Map.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_Map.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_MapIndexed.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_MapIndexed.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_MapIndexed.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_connect.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_connect.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_connect.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_cva.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_cva.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_cva.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_cvi.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_cvi.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_cvi.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_dirname.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_dirname.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_dirname.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_fast_operators.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_fast_operators.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_fast_operators.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_lambertw.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_lambertw.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_lambertw.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_message.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_message.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_message.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_round.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_round.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_round.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_rows_cols_pos.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_rows_cols_pos.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_rows_cols_pos.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_sort.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_sort.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_sort.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
add_test([=[unittests/sli2py_ignore/test_spike_dilutor.sli]=] "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/bin/nest" "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator-install/share/doc/nest/unittests/sli2py_ignore/test_spike_dilutor.sli")
set_tests_properties([=[unittests/sli2py_ignore/test_spike_dilutor.sli]=] PROPERTIES  _BACKTRACE_TRIPLES "/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;24;add_test;/p/home/jusers/linssen1/jusuf/NestBenchmark/nest-simulator/testsuite/unittests/sli2py_ignore/CMakeLists.txt;0;")
