# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/p/project/cslns/babu1/NestBenchmark/Running/target_plastic;/p/project/cslns/babu1/NestBenchmark/Running/target_plastic")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/p/software/jurecadc/stages/2024/software/CMake/3.26.3-GCCcore-12.3.0/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "nestmlplasticmodule built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "\\.gitignore;\\.git/;\\.travis\\.yml;/build/;/_CPack_Packages/;CMakeFiles/;cmake_install\\.cmake;Makefile.*;CMakeCache\\.txt;CPackConfig\\.cmake;CPackSourceConfig\\.cmake")
set(CPACK_INSTALLED_DIRECTORIES "/p/project/cslns/babu1/NestBenchmark/Running/target_plastic;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/p/project/cslns/babu1/nest-simulator-install")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "nestmlplasticmodule 1.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "nestmlplasticmodule 1.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/p/software/jurecadc/stages/2024/software/binutils/2.40-GCCcore-12.3.0/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/p/software/jurecadc/stages/2024/software/binutils/2.40-GCCcore-12.3.0/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/p/project/cslns/babu1/NestBenchmark/Running/target_plastic/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/p/software/jurecadc/stages/2024/software/CMake/3.26.3-GCCcore-12.3.0/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "NEST Module nestmlplasticmodule")
set(CPACK_PACKAGE_FILE_NAME "nestmlplasticmodule")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "nestmlplasticmodule 1.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "nestmlplasticmodule 1.0")
set(CPACK_PACKAGE_NAME "nestmlplasticmodule")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "NEST Initiative (http://www.nest-initiative.org/)")
set(CPACK_PACKAGE_VERSION "1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/p/software/jurecadc/stages/2024/software/binutils/2.40-GCCcore-12.3.0/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/p/software/jurecadc/stages/2024/software/CMake/3.26.3-GCCcore-12.3.0/share/cmake-3.26/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/p/software/jurecadc/stages/2024/software/CMake/3.26.3-GCCcore-12.3.0/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/p/software/jurecadc/stages/2024/software/CMake/3.26.3-GCCcore-12.3.0/share/cmake-3.26/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "\\.gitignore;\\.git/;\\.travis\\.yml;/build/;/_CPack_Packages/;CMakeFiles/;cmake_install\\.cmake;Makefile.*;CMakeCache\\.txt;CPackConfig\\.cmake;CPackSourceConfig\\.cmake")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/p/project/cslns/babu1/NestBenchmark/Running/target_plastic;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/p/project/cslns/babu1/NestBenchmark/Running/target_plastic/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "nestmlplasticmodule")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/p/project/cslns/babu1/NestBenchmark/Running/target_plastic/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
